### ISSUE TITLE
[Audiences] Fix edit Segment FilterClick()

### ISSUE THREAD

**Issue by daver78** [coa0329/Bhaang#114]
@coa0329 when I updated `editContactAudience.html`, I wanted to allow the User to see the filter on the screen without having to hit the button you had there previously.

Since I was pressed for time, I did this: 

```
<script>
$(window).load(function() {
FilterClick();
});
</script>

```
... but it doesn't always seem to work (meaning, sometimes the page does not show my saved filter rows).  

Can you fix this properly instead of my hack?

**Comment by daver78** [comment]
@paagla123 Tagging you as reference for the mixed up soup of information you originally had :)

**Comment by coa0329** [comment]
This issue was moved to coa0329/BhaangWeb#1

**Comment by coa0329** [comment]
Fixed on stage.

**Comment by daver78** [comment]
@paagla123 You will verify this fix on stage?

**Comment by paagla123** [comment]
@daver78 @coa0329 We don;t need to click any button to see the filters on Firefox. But the filters still do not show up on Chrome - in Staging. So not fixed, I would say.

**Comment by coa0329** [comment]
![143](https://user-images.githubusercontent.com/7914690/30571346-3ffd5d32-9d11-11e7-8ad5-78c425790d8b.JPG)


I cannot repeat it.
The filter show up on my Chrome.

**Comment by paagla123** [comment]
Retested - fixed.
