### ISSUE TITLE
eBook Missing content when program is published

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#123]
No content in the html pages - microsite or email

**Comment by coa0329** [comment]
Fixed on stage.

**Comment by paagla123** [comment]
@coa0329 OK we have content for landing pages now. However, when we visit the URL this is how it shows:
![image](https://user-images.githubusercontent.com/29718335/30840256-10717f70-a22b-11e7-8856-8ae34817c687.png)

**Comment by paagla123** [comment]
I can see email content but cannot test because microsite is not displaying correctly

**Comment by coa0329** [comment]
This is the same as https://github.com/coa0329/BhaangWeb/issues/24

**Comment by coa0329** [comment]
Fixed on stage for eBook.

Please create the new campaign when you test.

**Comment by paagla123** [comment]
@coa0329 all page contents seem hard coded to http://davincistage.mindfireis.com/admin/login.html so we get to the login page in daVinci

**Comment by coa0329** [comment]
Yes, It will render to the link to S3 when you save each page, email.

**Comment by paagla123** [comment]
Its not changing the value. I have tested twice. All pages are left with the same value of  http://davincistage.mindfireis.com/admin/login.html. See screenshot here - after publish from daVinci.
![image](https://user-images.githubusercontent.com/29718335/30891059-aa92739c-a2e5-11e7-95ec-3d511da52f6d.png)

**Comment by coa0329** [comment]
Which campaign ?

Please specify when you report the issue next time.

**Comment by coa0329** [comment]
Fixed on stage.

**Comment by paagla123** [comment]
@coa0329 @paweenwich this is only partially fixed. The landing pages show up correctly, but not the emails. I assume this will get fixed along with #129 - is that right?
