### ISSUE TITLE
Blog - I can no longer save and launch email3 after I have launched the campaign with the first two emails

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#128]
I used to be able to do that. To reproduce:
Create and schedule the first two emails and Launch.
Now create the 3rd email ad save. Create schedule for 3rd email - you can no longer save it - it just circles and can't launch either.
Ha-ma-da!

**Comment by coa0329** [comment]
Fixed on stage.

**Comment by paagla123** [comment]
@coa0329 this is not fixed on stage. In fact, once the campaign is published, you cannot change or add to schedule. Try changing schedule or adding a 3rd email to KD-0925-Blog-01PM under daVinci, logged in as kdutta

**Comment by coa0329** [comment]
I cannot repeat it.

I can add email3 and change schedule in all emails.

![153](https://user-images.githubusercontent.com/7914690/30840992-7c80592e-a2a4-11e7-9589-5ad83f45c4dd.JPG)

![154](https://user-images.githubusercontent.com/7914690/30840995-813691b8-a2a4-11e7-8886-9cc1cf1b6a5a.JPG)

**Comment by paagla123** [comment]
The scenario was I could not add email3 after emails 1 & 2 went out. That is the most likely scenario. I will retest

**Comment by paagla123** [comment]
@coa0329 test ok on stage - thank you.

**Comment by paagla123** [comment]
Re launch is fine - schedules of new emails a problem. I have opened a new issue under bhangweb/#97
