### ISSUE TITLE
Content not correctly displayed for View in Browser for emails in Blog

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#129]
When I click on View in Browser for Email1 of Blog, we get the following on screen:
![image](https://user-images.githubusercontent.com/29718335/30839346-2a59c492-a226-11e7-9d40-80721ba33c9a.png)

The domain appears to be wrong. In Studio we see 
![image](https://user-images.githubusercontent.com/29718335/30839371-4600ab7a-a226-11e7-93d7-498c15d58136.png)

In the browser, the domain we see is different - it is http://kushaldutta926.davinci16916.m.mdl.io/21b0750b127b8352f4ad6e3f66cd3650/Email1.html - see teh first screenshot above.

**Comment by coa0329** [comment]
Which campaign ?

**Comment by paagla123** [comment]
Sorry I was looking at the wrong campaign!

**Comment by paagla123** [comment]
@coa0329 did we address this when we worked on the eBook?

**Comment by coa0329** [comment]
![149](https://user-images.githubusercontent.com/7914690/30890188-8aa3636e-a355-11e7-95e5-67772410cd3a.JPG)


The domain in studio is davinci16916.m.mdl.io/21b0750b127b8352f4ad6e3f66cd3650

**Comment by paagla123** [comment]
@coa0329 I just retested everything. I have the new campaign published KD-0926-Blog-03. When I clicked on the View in Browser link I got this screenshot pasted below. The content is still going through ##email1content## as I see. The actual S3 location is perfect, I think somehow the variable has been left behind and causing the issue. Pl fix. Also - pl note that you have to mark one of the pages as a home page - does not matter which one, since we are accessing the pages by full URL.
![image](https://user-images.githubusercontent.com/29718335/30890700-48092d3a-a2e3-11e7-8edd-bb541b002940.png)

**Comment by coa0329** [comment]
We fixed eBook yesterday.

We will fix Blog today.

**Comment by paagla123** [comment]
@coa0329 pl make sure you mark a page a home page in the microsite for blog.
eBook not fixed - see my comments on that issue pl.

**Comment by coa0329** [comment]
Which issue ? Please specify.

**Comment by paagla123** [comment]
@coa0329 #123

**Comment by paagla123** [comment]
@coa0329 please calm down and go through everything one by one. I have spent all day testing and I know what I am talking about. This screenshot is from eBook - that one has hoe page. The Blog is missing a home page.

**Comment by coa0329** [comment]
The Blog is missing a home page. 
- Fixed on stage

Kwang is working on ##emailXcontent## in microsite.

**Comment by paagla123** [comment]
@paweenwich what is your ETA on this one? We're running out of time for Martech. Would like to freeze code in production by Friday. Thx

**Comment by paweenwich** [comment]
This thing will work today.

**Comment by paagla123** [comment]
@paweenwich I like your confidence. :-)

**Comment by coa0329** [comment]
Fixed on stage.
