### ISSUE TITLE
Notifications and Alerts

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#41]
@coa0329 when we select Visit My Blog Post, te click email trigger needs to change status to START. It is not doing so.

@daver78 can you please check if you have received two open email alerts for John Shind?

Thanks

**Comment by paagla123** [comment]
@coa0329 I have tested again - the click alert email does not change to start even though visit my blog is selected alerts section. Pl see screenshots below.
![image](https://user-images.githubusercontent.com/29718335/29919609-da5662f6-8dfe-11e7-9b85-5c4d2dbf6b99.png)
![image](https://user-images.githubusercontent.com/29718335/29919664-0b7825ea-8dff-11e7-8738-8c27bfd8c375.png)

**Comment by coa0329** [comment]
Fixed

**Comment by paagla123** [comment]
@coa0329 this is still not working correctly. I assume you did not get to it.

**Comment by coa0329** [comment]
@paagla123 Fixed.

**Comment by paagla123** [comment]
FIXED Closing
