### ISSUE TITLE
Remove Save message box and using inline notify message instead

### ISSUE THREAD

**Issue by paweenwich** [coa0329/Bhaang#9]
Item from feature 8/24 feature_backlog.txt )

Dave suggest evaluating the built-in options here: http://webapplayers.com/inspinia_admin-v2.7.1/loading_buttons.html

**Comment by daver78** [comment]
@paweenwich and @coa0329, is my suggestion enough or do you need some sort of mockup?

**Comment by paweenwich** [comment]
@daver78 This is ok.  No mockup needed.  Thank you.

**Comment by daver78** [comment]
@paweenwich OK.  After you have the team implement it in a location, can you let me know so I can take a look?  Then we can apply the same style everywhere (where it makes sense ... maybe not be every "save", only some).

**Comment by paweenwich** [comment]
@daver78 Please take a look at, "Identify target blog post", "Warite you Email" and "Choose your Audience"

**Comment by daver78** [comment]
@paweenwich I think that is OK.  @paagla123 you see any issue with this?

**Comment by paagla123** [comment]
@paweenwich @daver78 this works in most places. There are areas where this does not work need to be corrected:
1) Save for second and third emails.
2) After launch, there is the big box saying PUBLISH SUCCESSFUL or STUDIO RETURN ERROR. I don't think we need the PUBLISH SUCCESSFUL confirmation any more - do we? I suggest we just print thec Launch Successful message underneath the button, or in the status bar?
The error should be returned - should say, Program Launch Failed. This is one area where we need to look at the error codes and figure out a simpler message. 
I looked at the return message. Here's the JSON that's coming back from Studio.
Result	Object
ErrorCode	"DuplicateProgramName;"
ErrorMessage	"[i]Looks like you already hav…ther name and try again!\r\n"
ExceptionMessage	""
Why ca't we just display the error code and message somewhere for now? I will come up with a better message later on.

**Comment by paagla123** [comment]
@AumpaiFung the save button in Audience should follow the same styling please.

**Comment by paweenwich** [comment]
Done please check

**Comment by paagla123** [comment]
@paweenwich which one is done. Launch button or Save in audience or both?

**Comment by paagla123** [comment]
Save Audience is done correctly - I have verified. @AumpaiFung please remove debug messages from the code, so that I can close this.

**Comment by AumpaiFung** [comment]
@paagla123  I fixed it.

**Comment by paagla123** [comment]
@paweenwich SAVE button still not working correctly in 2nd and 3rd emails.

**Comment by paagla123** [comment]
@paweenwich Launch error message and alert box for save not changed yet.

**Comment by paagla123** [comment]
@AumpaiFung removed the alert boxes with debug messages, so I am going to close this issue. What's left here is covered n issue#29 associated with checkin, checkout and republish. In face, we do want to have the error or success message in that scenario.

**Comment by daver78** [comment]
@paagla123 "In face?"  Means "in fact" ... or do you mean in the "UI"?

**Comment by paagla123** [comment]
@daver78 Yes - IN Fact we should have the success or failure message with the error information as applicable show up in the UI - right?

**Comment by daver78** [comment]
@paagla123 Yes, that's what you sparked in my mind. 

I can see a nice way to show this, but unsure if it "fits" because I'm still not 100% clear on how you are proposing we handle "Launch" (first publish )versus the ongoing "Updates" (check out, check in) that are required as Users edit the applicable portions.
